name: Bug Report
description: Create a bug report for the Web Analytics Starter Kit
title: "[Bug] "
labels: ["bug", "triage"]
assignees:
  - alejandromav
  - kukukaka
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module is not working as expected?
      options:
        - Dashboard
        - Tracker
        - Middleware
        - Tinybird Data Project
        - Other, I don't know
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Details
      description: What browser are you using?, How are you deploying your application? (if relevant)
    validations:
      required: false
  - type: markdown
    attributes:
      value: Before posting the issue go through the steps you've written down to make sure the steps provided are detailed and clear.
  - type: markdown
    attributes:
      value: Contributors should be able to follow the steps provided in order to reproduce the bug.
  - type: markdown
    attributes:
      value: These steps are used to add integration tests to ensure the same issue does not happen again. Thanks in advance!
